version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - yum install -y wget unzip
      - wget https://releases.hashicorp.com/terraform/1.9.3/terraform_1.9.3_linux_amd64.zip
      - unzip terraform_1.9.3_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version

  build:
    commands:
      - echo "Terraform Init"
      - terraform init
      - echo "Destroying Terraform Resources"
      - terraform destroy -auto-approve

  post_build:
    commands:
      - echo "Windows EC2 Instances Terminated Successfully."
